spring:
  datasource:
    url: jdbc:h2:mem:tododb
    username: user
    password: h2-user
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081